/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static javax.swing.text.html.HTML.Tag.OPTION;
import model.ContactInfo;
import model.Employee;
import util.IndexEmployees;

/**
 *
 * @author vrushaliphaltankar
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    Employee employee;
    String selectedImagePath;
    String month;
    String day;
    String year;
    
    public CreateJPanel(Employee employee) {
        
        initComponents();
        this.employee = employee;
        lblMonth.removeAllItems();
        lblDate.removeAllItems();
        lblYear.removeAllItems();
        
        
        lblMonth.addItem("Month");
        lblDate.addItem("Day");
        lblYear.addItem("Year");
        
        btnGender.removeAllItems();
        btnGender.addItem("Select");
        
        for(int i=1;i<=12;i++){
            
            if(i<10){
              lblMonth.addItem("0" + new Integer(i).toString());  
                
            }
     
            else{
                
              lblMonth.addItem(new Integer(i).toString());
                
            }
            
            
        }
        
        for(int j=1984;j<=2022;j++){
            
     
            lblYear.addItem(new Integer(j).toString());
            
        }
        
        for(int k=1;k<=31;k++){
            
            if(k<10){
              lblDate.addItem("0" + new Integer(k).toString());  
                
            }
     
            else{
                
              lblDate.addItem(new Integer(k).toString());
                
            }
            
        }
        
        btnGender.addItem("Male");
        btnGender.addItem("Female");
        btnGender.addItem("Not willing to disclose");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iblEmployee = new javax.swing.JLabel();
        iblName = new javax.swing.JLabel();
        iblEmployeeId = new javax.swing.JLabel();
        iblAge = new javax.swing.JLabel();
        iblGender = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmployeeId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        iblStartDate = new javax.swing.JLabel();
        iblLevel = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        iblTeamInfo = new javax.swing.JLabel();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        iblPhoto = new javax.swing.JLabel();
        iblPositionTitle = new javax.swing.JLabel();
        iblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtImage = new javax.swing.JButton();
        txtBrowse = new javax.swing.JLabel();
        lblMonth = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JComboBox<>();
        lblYear = new javax.swing.JComboBox<>();
        btnGender = new javax.swing.JComboBox<>();
        iblPhone = new javax.swing.JLabel();

        iblEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        iblEmployee.setText("Add New Employee");

        iblName.setText("Name");

        iblEmployeeId.setText("Employee ID");

        iblAge.setText("Age");

        iblGender.setText("Gender");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        iblStartDate.setText("Start Date");

        iblLevel.setText("Level");

        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });

        iblTeamInfo.setText("Team Info");

        txtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionTitleActionPerformed(evt);
            }
        });

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        iblPhoto.setText("Photo");

        iblPositionTitle.setText("Position Title");

        iblEmail.setText("Email");

        txtImage.setText("Browse");
        txtImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImageActionPerformed(evt);
            }
        });

        lblMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lblMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMonthActionPerformed(evt);
            }
        });

        lblDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        btnGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenderActionPerformed(evt);
            }
        });

        iblPhone.setText("Phone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(iblEmployee))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(iblName)
                                    .addComponent(iblEmployeeId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(iblAge)
                                    .addComponent(iblGender)
                                    .addComponent(iblPositionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(iblStartDate)
                                    .addComponent(iblTeamInfo)
                                    .addComponent(iblPhoto)
                                    .addComponent(iblLevel)
                                    .addComponent(iblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(iblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtImage)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAge)
                                    .addComponent(txtEmployeeId)
                                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDate, 0, 1, Short.MAX_VALUE))
                                            .addComponent(btnGender, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 555, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(iblEmployee)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblEmployeeId)
                            .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblGender)
                            .addComponent(btnGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblPhoto)
                    .addComponent(txtImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSave)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      Employee emp = new Employee();
      emp.setName(txtName.getText());
      
      String gender = (String)btnGender.getSelectedItem();
        if(((String)btnGender.getSelectedItem()).equalsIgnoreCase("Select")){
            
            gender = null;
        }
        
        String month = (String)lblMonth.getSelectedItem();
        String day = (String)lblDate.getSelectedItem();
        String year = (String)lblYear.getSelectedItem();
      
        if(month.equalsIgnoreCase("Month")){
            
            month = null;
        }
        
        if(day.equalsIgnoreCase("Day")){
            
            day = null;
        }
        
        if(year.equalsIgnoreCase("Year")){
            
            year = null;
        }
        
        String date = null;
        
        if(month!=null && day!=null && year!=null){
            
            date = month + "-" + day + "-" + year;
            
        }
        
      String regexEmployeeId = "^\\d{4}$";
      Pattern patternEmployeeId = Pattern.compile(regexEmployeeId);
      Matcher matcherEmployeeId = patternEmployeeId.matcher(txtEmployeeId.getText());
      
      if(!matcherEmployeeId.matches()){
          
          JOptionPane.showMessageDialog(this, "Enter your 4 digit Employee ID");
            throw new UnsupportedOperationException("Enter your 4 digit Employee ID");
      }
      emp.setEmpId(txtEmployeeId.getText());
      
      
      if(Integer.parseInt(txtAge.getText())<18){
          
          JOptionPane.showMessageDialog(this, "Employee should be above 18 years");
            throw new UnsupportedOperationException("Employee should be above 18 years");
            
      }
      emp.setAge(Integer.parseInt(txtAge.getText()));
      
      //month = (String)lblMonth.getSelectedItem();
      //day = (String)lblDate.getSelectedItem();
      //year = (String)lblYear.getSelectedItem();
      
      //String date = month + "-" + day + "-" + year;
      
      if(gender == null){
          
          JOptionPane.showMessageDialog(this, "Please select Gender");
            throw new UnsupportedOperationException("Please select Gender");
      }
      emp.setGender((String)btnGender.getSelectedItem());
      
      if(date == null){
          
          JOptionPane.showMessageDialog(this, "Please select correct Date");
            throw new UnsupportedOperationException("Please select correct Date");
      }
      
      emp.setStartDate(LocalDate.parse(date, DateTimeFormatter.ofPattern("MM-dd-yyyy")));
      
      if(Integer.parseInt(txtLevel.getText())<1 || Integer.parseInt(txtLevel.getText())>10){
          
          JOptionPane.showMessageDialog(this, "Level Should be 1 to 10");
            throw new UnsupportedOperationException("Level Should be 1 to 10");
          
      }
      emp.setLevel(Integer.parseInt(txtLevel.getText()));
      
      emp.setTeamInfo(txtTeamInfo.getText());
      emp.setPositionTitle(txtPositionTitle.getText());
      emp.setPhoto(selectedImagePath);
      
      String regexPhone = "^(\\d{3}[- .]?){2}\\d{4}$";
      Pattern patternPhone = Pattern.compile(regexPhone);
      Matcher matcherPhone = patternPhone.matcher(txtPhone.getText());
      
      if(!matcherPhone.matches()){
          
          JOptionPane.showMessageDialog(this, "Invalid Phone Number");
            throw new UnsupportedOperationException("Please enter correct Phone number");
      }
      
      ContactInfo contactInfo = new ContactInfo();
      contactInfo.setCell(txtPhone.getText());
      String regex = "^(.+)@(.+)$";
 
      Pattern pattern = Pattern.compile(regex);
      Matcher matcher = pattern.matcher(txtEmail.getText());
      
      if(!matcher.matches()){
          
          JOptionPane.showMessageDialog(this, "Invalid Email id");
            throw new UnsupportedOperationException("Please enter correct Email");
      }
      contactInfo.setEmail(txtEmail.getText());
      
      emp.setContactInfo(contactInfo); 
      
      IndexEmployees indexEmployess = new IndexEmployees();
      indexEmployess.indexEmployees(emp);
      
      JOptionPane.showMessageDialog(this, "Added new Employee");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void txtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionTitleActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void txtImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImageActionPerformed
        // TODO add your handling code here:
        
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png","jpeg","jpg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialog = browseImageFile.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
        
        File selectedImageFile = browseImageFile.getSelectedFile();
        selectedImagePath = selectedImageFile.getAbsolutePath();
        JOptionPane.showMessageDialog(null, selectedImagePath);
        
        ImageIcon ii = new ImageIcon(selectedImagePath);
        
        Image image = ii.getImage().getScaledInstance(txtBrowse.getWidth(), txtBrowse.getHeight(), Image.SCALE_SMOOTH);
        txtBrowse.setIcon(new ImageIcon(image));
        
    }
        
    }//GEN-LAST:event_txtImageActionPerformed

    private void lblMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMonthActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenderActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> btnGender;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel iblAge;
    private javax.swing.JLabel iblEmail;
    private javax.swing.JLabel iblEmployee;
    private javax.swing.JLabel iblEmployeeId;
    private javax.swing.JLabel iblGender;
    private javax.swing.JLabel iblLevel;
    private javax.swing.JLabel iblName;
    private javax.swing.JLabel iblPhone;
    private javax.swing.JLabel iblPhoto;
    private javax.swing.JLabel iblPositionTitle;
    private javax.swing.JLabel iblStartDate;
    private javax.swing.JLabel iblTeamInfo;
    private javax.swing.JComboBox<String> lblDate;
    private javax.swing.JComboBox<String> lblMonth;
    private javax.swing.JComboBox<String> lblYear;
    private javax.swing.JTextField txtAge;
    private javax.swing.JLabel txtBrowse;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JButton txtImage;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
