/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Employee;
import model.Employees;
import util.IndexEmployees;

/**
 *
 * @author vrushaliphaltankar
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJFrame
     */
    Employee employee;
    String selectedImagePath;
    public UpdateJPanel(Employee employee) {
        initComponents();
        this.employee = employee;
        selectedImagePath = null;
        
        lblMonth.removeAllItems();
        lblDate.removeAllItems();
        lblYear.removeAllItems();
        
        
        lblMonth.addItem("Month");
        lblDate.addItem("Day");
        lblYear.addItem("Year");
        btnGender.removeAllItems();
        btnGender.addItem("Select");
        
        for(int i=1;i<=12;i++){
            
            if(i<10){
              lblMonth.addItem("0" + new Integer(i).toString());  
                
            }
     
            else{
                
              lblMonth.addItem(new Integer(i).toString());
                
            }
            
            
        }
        
        for(int j=1984;j<=2022;j++){
            
     
            lblYear.addItem(new Integer(j).toString());
            
        }
        
        for(int k=1;k<=31;k++){
            
            if(k<10){
              lblDate.addItem("0" + new Integer(k).toString());  
                
            }
     
            else{
                
              lblDate.addItem(new Integer(k).toString());
                
            }
            
        }
        
        btnGender.addItem("Male");
        btnGender.addItem("Female");
        btnGender.addItem("Not willing to disclose");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        iblEmployee = new javax.swing.JLabel();
        iblGender = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtImage = new javax.swing.JButton();
        txtEmployeeId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        lblMonth = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JComboBox<>();
        iblStartDate = new javax.swing.JLabel();
        lblYear = new javax.swing.JComboBox<>();
        iblLevel = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        iblTeamInfo = new javax.swing.JLabel();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        btnGender = new javax.swing.JComboBox<>();
        txtPhone = new javax.swing.JTextField();
        iblPhone = new javax.swing.JLabel();
        iblPhoto = new javax.swing.JLabel();
        iblPositionTitle = new javax.swing.JLabel();
        iblEmail = new javax.swing.JLabel();
        iblName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        iblEmployeeId = new javax.swing.JLabel();
        iblAge = new javax.swing.JLabel();
        txtBrowse = new javax.swing.JLabel();

        btnSave.setText("Update");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        iblEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        iblEmployee.setText("Update Employee");

        iblGender.setText("Gender");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtImage.setText("Browse");
        txtImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImageActionPerformed(evt);
            }
        });

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });

        lblMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lblMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblMonthActionPerformed(evt);
            }
        });

        lblDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        iblStartDate.setText("Date");

        lblYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lblYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblYearActionPerformed(evt);
            }
        });

        iblLevel.setText("Level");

        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });

        iblTeamInfo.setText("Team Info");

        txtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPositionTitleActionPerformed(evt);
            }
        });

        btnGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        btnGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenderActionPerformed(evt);
            }
        });

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        iblPhone.setText("Phone");

        iblPhoto.setText("Photo");

        iblPositionTitle.setText("Position Title");

        iblEmail.setText("Email");

        iblName.setText("Name");

        iblEmployeeId.setText("Employee ID");

        iblAge.setText("Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iblName)
                            .addComponent(iblEmployeeId)
                            .addComponent(iblGender)
                            .addComponent(iblStartDate)
                            .addComponent(iblLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblTeamInfo)
                            .addComponent(iblPositionTitle)
                            .addComponent(iblPhone)
                            .addComponent(iblEmail)
                            .addComponent(iblPhoto)
                            .addComponent(iblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImage)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(btnSave)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(iblEmployee)
                .addGap(315, 315, 315))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(iblEmployee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblEmployeeId)
                    .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iblLevel)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iblTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(iblPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iblPositionTitle))
                        .addGap(18, 18, 18)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iblEmail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblPhoto)
                    .addComponent(txtImage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(txtBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                if((null == txtName.getText() || txtName.getText().isEmpty())
                && (null == txtEmployeeId.getText() || txtEmployeeId.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(this, "Please enter employee Name or Employee ID");
            throw new UnsupportedOperationException("Missing mandatory fields");
        }
        
        String gender = (String)btnGender.getSelectedItem();
        if(((String)btnGender.getSelectedItem()).equalsIgnoreCase("Select")){
            
            gender = null;
        }
        
        String month = (String)lblMonth.getSelectedItem();
        String day = (String)lblDate.getSelectedItem();
        String year = (String)lblYear.getSelectedItem();
      
        if(month.equalsIgnoreCase("Month")){
            
            month = null;
        }
        
        if(day.equalsIgnoreCase("Day")){
            
            day = null;
        }
        
        if(year.equalsIgnoreCase("Year")){
            
            year = null;
        }
        
        String date = null;
        
        if(month!=null && day!=null && year!=null){
            
            date = month + "-" + day + "-" + year;
            
        }
        
      
        Employees employees = Employees.getInstance();
        
        Employee emp = null;
        
        if(!(txtName.getText() == null || txtName.getText().isEmpty()))
        {
            emp = employees.getNameToEmployee().get(txtName.getText());
        }
        
        if(!(txtEmployeeId.getText() == null || txtEmployeeId.getText().isEmpty()))
        {
            String regexEmployeeId = "^\\d{4}$";
            Pattern patternEmployeeId = Pattern.compile(regexEmployeeId);
            Matcher matcherEmployeeId = patternEmployeeId.matcher(txtEmployeeId.getText());
      
            if(!matcherEmployeeId.matches()){
          
                JOptionPane.showMessageDialog(this, "Enter your 4 digit Employee ID");
                  throw new UnsupportedOperationException("Enter your 4 digit Employee ID");
            }
            emp = employees.getEmpIdToEmployee().get(txtEmployeeId.getText());
        }
        
        if(null == emp)
        {
            JOptionPane.showMessageDialog(this, "Please Add Employee to the System");
            throw new UnsupportedOperationException("No Employee exist in the System");
        }
        
        if(!(txtAge.getText() == null || txtAge.getText().isEmpty()))
        {
            if(Integer.parseInt(txtAge.getText())<18){
          
                JOptionPane.showMessageDialog(this, "Employee should be above 18 years");
                  throw new UnsupportedOperationException("Employee should be above 18 years");
            
      }
            emp.setAge(Integer.parseInt(txtAge.getText()));
        }
        
        if(!(gender == null || gender.isEmpty()))
        {
            emp.setGender(gender);
        }
        
        if(!(date == null || date.isEmpty()))
        {
            emp.setStartDate(LocalDate.parse(date, DateTimeFormatter.ofPattern("MM-dd-yyyy")));
        }
        
        if(!(txtLevel.getText() == null || txtLevel.getText().isEmpty()))
        {
            if(Integer.parseInt(txtLevel.getText())<1 || Integer.parseInt(txtLevel.getText())>=10){
          
                JOptionPane.showMessageDialog(this, "Level Should be 1 to 10");
                throw new UnsupportedOperationException("Level Should be 1 to 10");
          
            }
           emp.setLevel(Integer.parseInt(txtLevel.getText()));
        }
        
        if(!(txtTeamInfo.getText() == null || txtTeamInfo.getText().isEmpty()))
        {
           emp.setTeamInfo(txtTeamInfo.getText());
        }
        
        if(!(txtPositionTitle.getText() == null || txtPositionTitle.getText().isEmpty()))
        {
           emp.setPositionTitle(txtPositionTitle.getText());
        }
        
        if(!(txtPhone.getText() == null || txtPhone.getText().isEmpty()))
        {
            
            String regexPhone = "^(\\d{3}[- .]?){2}\\d{4}$";
            Pattern patternPhone = Pattern.compile(regexPhone);
            Matcher matcherPhone = patternPhone.matcher(txtPhone.getText());
      
            if(!matcherPhone.matches()){
          
                JOptionPane.showMessageDialog(this, "Invalid Phone Number");
                  throw new UnsupportedOperationException("Please enter correct Phone number");
            }
           emp.getContactInfo().setCell(txtPhone.getText());
        }
        
        if(!(txtEmail.getText() == null || txtEmail.getText().isEmpty()))
        {
            String regex = "^(.+)@(.+)$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(txtEmail.getText());
            
            if(!matcher.matches()){

            JOptionPane.showMessageDialog(this, "Invalid Email id");
            throw new UnsupportedOperationException("Please enter correct Email");
        }
            emp.getContactInfo().setEmail(txtEmail.getText());
    }
        
        if(!(selectedImagePath == null || selectedImagePath.isEmpty())){
            
            emp.setPhoto(selectedImagePath);
        }

        IndexEmployees indexEmployess = new IndexEmployees();
        indexEmployess.indexEmployees(emp);

        JOptionPane.showMessageDialog(this, "Updated Employee Details");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImageActionPerformed
        // TODO add your handling code here:

        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png","jpeg","jpg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialog = browseImageFile.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION) {
        
        File selectedImageFile = browseImageFile.getSelectedFile();
        selectedImagePath = selectedImageFile.getAbsolutePath();
        JOptionPane.showMessageDialog(null, selectedImagePath);
        
        ImageIcon ii = new ImageIcon(selectedImagePath);
        
        Image image = ii.getImage().getScaledInstance(txtBrowse.getWidth(), txtBrowse.getHeight(), Image.SCALE_SMOOTH);
        txtBrowse.setIcon(new ImageIcon(image));

        }

    }//GEN-LAST:event_txtImageActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void lblMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMonthActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void txtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionTitleActionPerformed

    private void btnGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenderActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void lblYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> btnGender;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel iblAge;
    private javax.swing.JLabel iblEmail;
    private javax.swing.JLabel iblEmployee;
    private javax.swing.JLabel iblEmployeeId;
    private javax.swing.JLabel iblGender;
    private javax.swing.JLabel iblLevel;
    private javax.swing.JLabel iblName;
    private javax.swing.JLabel iblPhone;
    private javax.swing.JLabel iblPhoto;
    private javax.swing.JLabel iblPositionTitle;
    private javax.swing.JLabel iblStartDate;
    private javax.swing.JLabel iblTeamInfo;
    private javax.swing.JComboBox<String> lblDate;
    private javax.swing.JComboBox<String> lblMonth;
    private javax.swing.JComboBox<String> lblYear;
    private javax.swing.JTextField txtAge;
    private javax.swing.JLabel txtBrowse;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JButton txtImage;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
